/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package koneksidatabase;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author MuhAgungN173
 */
public final class FormArrayTabelSederhana extends javax.swing.JFrame {

    private int selectedRow;
    private int index = 0;

    /**
     * Creates new form frmArrayTabelSederhana
     *
     * @throws java.sql.SQLException
     */
    public FormArrayTabelSederhana() throws SQLException {
        super("PEMROGRAMAN APLIKASI JAVA");
        initComponents();
        this.viewDataBank();
        this.pilih();
    }

    class MyList implements ListSelectionListener {

        @Override
        public void valueChanged(ListSelectionEvent e) {
            if (e.getValueIsAdjusting()) {
                return;
            }
            ListSelectionModel lsm = (ListSelectionModel) e.getSource();
            selectedRow = lsm.getMinSelectionIndex();
            TableModel tb = tblHasil.getModel();
            tfKode.setText(tb.getValueAt(selectedRow, 0).toString());
            tfNama.setText(tb.getValueAt(selectedRow, 1).toString());
            tfDeskripsi.setText(tb.getValueAt(selectedRow, 2).toString());
           // tfKode.setEditable(false);
        }
    }

    void pilih() {
        tblHasil.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        ListSelectionModel rowSM = tblHasil.getSelectionModel();
        rowSM.addListSelectionListener(new MyList());

    }

    final void viewDataBank() throws SQLException {
        index = 0;
        DefaultTableModel model;
        model = (DefaultTableModel) tblHasil.getModel();
        DBConnect connect = new DBConnect();
        Object[][] data = connect.getDataBank();
        if (model.getRowCount() == 0) {
            Object[] row;
            for (int i = 0; i < connect.getCountBank(); i++) {
                row = new Object[]{data[i][0], data[i][1], data[i][2]};
                model.addRow(row);
                index++;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblHasil = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfKode = new javax.swing.JTextField();
        tfNama = new javax.swing.JTextField();
        tfDeskripsi = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblHasil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode", "Nama", "Deskripsi"
            }
        ));
        jScrollPane1.setViewportView(tblHasil);

        jLabel1.setText("Kode");

        jLabel2.setText("Nama");

        jLabel3.setText("Deskripsi");

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfKode, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                            .addComponent(tfNama)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnUbah)
                                .addGap(18, 18, 18)
                                .addComponent(btnTambah)
                                .addGap(18, 18, 18)
                                .addComponent(btnHapus)
                                .addGap(0, 33, Short.MAX_VALUE))
                            .addComponent(tfDeskripsi))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfDeskripsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah)
                    .addComponent(btnHapus)
                    .addComponent(btnUbah))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tb;
        tb = (DefaultTableModel) tblHasil.getModel();
        String kode = tfKode.getText();
        String nama = tfNama.getText();
        String deskripsi = tfDeskripsi.getText();
        tb.setValueAt(kode, selectedRow, 0);
        tb.setValueAt(nama, selectedRow, 1);
        tb.setValueAt(deskripsi, selectedRow, 2);
        DBConnect connect = null;
        try {
            connect = new DBConnect();
        } catch (SQLException ex) {
            Logger.getLogger(FormArrayTabelSederhana.class.getName()).log(Level.SEVERE, null, ex);
        }
        connect.updateBank(nama, deskripsi, tb.getValueAt(selectedRow, 0).toString());
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        String kode = tfKode.getText();
        String nama = tfNama.getText();
        String deskripsi = tfDeskripsi.getText();
        tfKode.setText("");
        tfNama.setText("");
        tfDeskripsi.setText("");
        DBConnect connect = null;
        try {
            connect = new DBConnect();
        } catch (SQLException ex) {
            Logger.getLogger(FormArrayTabelSederhana.class.getName()).log(Level.SEVERE, null, ex);
        }
        connect.setDataBank(kode, nama, deskripsi);
        DefaultTableModel model;
        model = (DefaultTableModel) tblHasil.getModel();
        Object[] row;
        row = new Object[]{kode, nama, deskripsi};
        model.addRow(row);
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tb;
        tb = (DefaultTableModel) tblHasil.getModel();
        int kd = Integer.parseInt(tb.getValueAt(selectedRow, 0).toString());

        for (int i = selectedRow; i < index - 1; i++) {
            tb.setValueAt(tb.getValueAt(i + 1, 0), i, 0);
            tb.setValueAt(tb.getValueAt(i + 1, 1), i, 1);
            tb.setValueAt(tb.getValueAt(i + 1, 2), i, 2);
        }
        tb.setValueAt("", selectedRow, 0);
        tb.setValueAt("", selectedRow, 1);
        tb.setValueAt("", selectedRow, 2);
        index--;
        tfKode.setText("");
        tfNama.setText("");
        tfDeskripsi.setText("");
        DBConnect connect = null;
        try {
            connect = new DBConnect();

        } catch (SQLException ex) {
            Logger.getLogger(FormArrayTabelSederhana.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
        connect.deleteBank(kd);
    }//GEN-LAST:event_btnHapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormArrayTabelSederhana.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormArrayTabelSederhana.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormArrayTabelSederhana.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormArrayTabelSederhana.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new FormArrayTabelSederhana().setVisible(true);

            } catch (SQLException ex) {
                Logger.getLogger(FormArrayTabelSederhana.class
                        .getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblHasil;
    private javax.swing.JTextField tfDeskripsi;
    private javax.swing.JTextField tfKode;
    private javax.swing.JTextField tfNama;
    // End of variables declaration//GEN-END:variables
}
